# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

#Plugins
plugins: [jekyll-paginate]

# Setup
title:            Marginal Futility
tagline:          'My favorite color is math'
description:      'Thoughts on Swift and other good stuff.'
url:              http://marginalfutility.net
baseurl:          ""

author:
  name:           'Jeff Blagdon'
  url:            https://twitter.com/blagdon

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
